AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating S3 buckets with public access and policies

Resources:
  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-raw-canbuddy
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-staging-canbuddy
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-processed-canbuddy
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  StagingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StagingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${StagingBucket}/*'

  ProcessedBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProcessedBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${ProcessedBucket}/*'

Outputs:
  RawBucketName:
    Description: Name of the raw S3 bucket
    Value: !Ref RawBucket

  StagingBucketName:
    Description: Name of the staging S3 bucket
    Value: !Ref StagingBucket

  ProcessedBucketName:
    Description: Name of the processed S3 bucket
    Value: !Ref ProcessedBucket
