AWSTemplateFormatVersion: "2010-09-09"
Description: An example template for scheduling a Step Functions state machine using EventBridge.

Resources:
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: CanBuddyStateMachine
      DefinitionString: |
        {
          "Comment": "A description of my state machine",
          "StartAt": "Lambda Invoke",
          "States": {
            "Lambda Invoke": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "OutputPath": "$.Payload",
              "Parameters": {
                "Payload.$": "$",
                "FunctionName": "arn:aws:lambda:us-east-1:251602527416:function:FetchLambdaCanBuddy:$LATEST"
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "Next": "Glue StartJobRun"
            },
            "Glue StartJobRun": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun",
              "Parameters": {
                "JobName": "Glue_CanBuddy"
              },
              "Next": "Lambda Invoke (1)"
            },
            "Lambda Invoke (1)": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "OutputPath": "$.Payload",
              "Parameters": {
                "Payload.$": "$",
                "FunctionName": "arn:aws:lambda:us-east-1:251602527416:function:ProcessFilesLambdaCanBuddy:$LATEST"
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "End": true
            }
          }
        }
      RoleArn: arn:aws:iam::251602527416:role/LabRole

  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Scheduled rule to run CanBuddyStateMachine every 2 minutes"
      ScheduleExpression: "rate(2 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt MyStateMachine.Arn
          Id: "CanBuddyStateMachineTarget"
          RoleArn: arn:aws:iam::251602527416:role/LabRole

Outputs:
  StateMachineARN:
    Description: The ARN of the created Step Functions state machine
    Value: !GetAtt MyStateMachine.Arn
